import { Asset, AuditLog, ServiceRecord, CompanySetting, UserProfile } from '../types';
import { calculateAssetAge, calculateDepreciatedValue, calculateExpectedReplacementDate, checkWarrantyAlert, checkReplacementAlert } from '../utils/assetUtils';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-sameer-tupe',
    email: 'sameer.tupe@accurate.in',
    name: 'Sameer Tupe',
    role: 'IT_MANAGER',
    designation: 'IT Manager / Super Admin',
    organization: 'ALL',
    phone: '+91 98230 11223',
    avatarUrl: '',
    lastLogin: '2026-08-19 09:30 AM',
    active: true,
    allowedCompanies: ['AGIPL', 'ASSPL', 'ONYX'],
  },
  {
    id: 'user-rahul-prasad',
    email: 'rahulprashad7@gmail.com',
    name: 'Rahul Prasad',
    role: 'IT_SUPPORT',
    designation: 'IT Support Specialist',
    organization: 'ALL',
    phone: '+91 97654 44321',
    avatarUrl: '',
    lastLogin: '2026-08-19 10:15 AM',
    active: true,
    allowedCompanies: ['AGIPL', 'ASSPL', 'ONYX'],
  },
  {
    id: 'user-auditor-1',
    email: 'audit.team@accurate.in',
    name: 'Priya Joshi',
    role: 'AUDITOR',
    designation: 'Internal IT Auditor',
    organization: 'ALL',
    phone: '+91 98811 55667',
    avatarUrl: '',
    lastLogin: '2026-08-18 04:00 PM',
    active: true,
    allowedCompanies: ['AGIPL', 'ASSPL', 'ONYX'],
  },
];

export const DEFAULT_USERS = INITIAL_USERS;

export const INITIAL_COMPANY_SETTINGS: CompanySetting[] = [
  {
    id: 'AGIPL',
    code: 'AGIPL',
    name: 'Accurate Gauging Instrument Pvt. Ltd.',
    address: '67, Hadapsar Industrial Estate, Pune, Maharashtra 411013',
    contactPerson: 'Sameer Tupe (IT Dept)',
    contactEmail: 'it.agipl@accurate.in',
    contactPhone: '+91 20 6603 5500',
    assetPrefix: 'AGIPL',
  },
  {
    id: 'ASSPL',
    code: 'ASSPL',
    name: 'Accurate Sales and Services Pvt. Ltd.',
    address: 'Plot No. 12, Pimpri MIDC, Pune, Maharashtra 411018',
    contactPerson: 'Rahul Prasad (IT Support)',
    contactEmail: 'it.asspl@accurate.in',
    contactPhone: '+91 20 2747 4300',
    assetPrefix: 'ASSPL',
  },
  {
    id: 'ONYX',
    code: 'ONYX',
    name: 'Onyx Precision',
    address: 'Survey 28/4, Chakan Industrial Phase II, Pune 410501',
    contactPerson: 'Sameer Tupe (IT Dept)',
    contactEmail: 'it.onyx@accurate.in',
    contactPhone: '+91 2135 667788',
    assetPrefix: 'ONYX',
  },
];

const rawAssetsData = [
  {
    id: 'agipl-dsk-001',
    assetId: 'AGIPL-DSK-001',
    company: 'AGIPL' as const,
    assetType: 'Desktop',
    assetNumber: 'AG-IT-2022-045',
    status: 'ACTIVE' as const,
    condition: 'NEW' as const,
    assignedEmployeeName: 'Vikas Kulkarni',
    assetUserName: 'vkulkarni',
    department: 'Engineering & Design',
    location: 'Hadapsar Plant - 1st Floor CAD Room',
    ipAddress: '192.168.10.45',
    serialNumber: 'DL-SN-9988231',
    manufacturer: 'Dell',
    model: 'OptiPlex 7090 Tower',
    processor: 'Intel Core i7-11700 (8 Core, 2.50 GHz to 4.90 GHz)',
    storage: '512GB NVMe SSD + 1TB Seagate Barracuda HDD',
    ram: '32GB DDR4 3200MHz',
    motherboard: 'Dell OEM Q570 Chipset',
    display: 'Dell UltraSharp 24 InfinityEdge (Dual Monitor)',
    displaySize: '24 inch x 2',
    lanCard: 'Intel Gigabit PCIe Ethernet I219-LM',
    upsBattery: 'APC Back-UPS Pro 1000VA',
    windowsVersion: 'Windows 11 Pro 23H2 64-bit',
    msOffice: 'Microsoft Office 2021 Home & Business',
    escan: 'eScan Corporate Edition (Active Lic #ESC-AG-889)',
    vendor: 'Softmart Solutions Pune',
    purchaseDate: '2022-06-15',
    purchaseCost: 85000,
    invoiceNumber: 'INV-SM-2022-7712',
    expectedLife: 5,
    warrantyStart: '2022-06-15',
    warrantyEnd: '2025-06-14',
    amcStart: '2025-06-15',
    amcEnd: '2026-06-14',
    lastServiceDate: '2024-03-10',
    remarks: 'SolidWorks CAD workstation with dedicated NVIDIA T1000 GPU.',
    createdAt: '2022-06-15 10:00:00',
    updatedAt: '2024-03-10 14:30:00',
    updatedBy: 'Sameer Tupe',
  },
  {
    id: 'agipl-lap-002',
    assetId: 'AGIPL-LAP-002',
    company: 'AGIPL' as const,
    assetType: 'Laptop',
    assetNumber: 'AG-IT-2023-112',
    status: 'ACTIVE' as const,
    condition: 'NEW' as const,
    assignedEmployeeName: 'Anjali Deshpande',
    assetUserName: 'adeshpande',
    department: 'Quality Assurance (QA/QC)',
    location: 'Hadapsar Plant - QA Lab',
    ipAddress: '192.168.10.88',
    serialNumber: 'HP-LAT-7430-881',
    manufacturer: 'HP',
    model: 'EliteBook 840 G9',
    processor: 'Intel Core i5-1240P (12 Core)',
    storage: '512GB PCIe NVMe SSD',
    ram: '16GB DDR5 4800MHz',
    motherboard: 'HP Integrated Alder Lake',
    display: '14" FHD IPS Anti-Glare (1920x1080) 400 nits',
    displaySize: '14 inch',
    lanCard: 'Intel Wi-Fi 6E AX211 + USB-C GbE Adapter',
    upsBattery: '51Wh 3-cell Li-ion (Health 92%)',
    windowsVersion: 'Windows 11 Pro 64-bit',
    msOffice: 'Microsoft Office 365 E3',
    escan: 'eScan Corporate Edition (Active Lic #ESC-AG-890)',
    vendor: 'Dynalog India Pvt Ltd',
    purchaseDate: '2023-08-20',
    purchaseCost: 92000,
    invoiceNumber: 'DYN-PUN-9921',
    expectedLife: 4,
    warrantyStart: '2023-08-20',
    warrantyEnd: '2026-08-19',
    amcStart: '',
    amcEnd: '',
    lastServiceDate: '2025-01-14',
    remarks: 'Used for CMM inspection reports and calibrated field testing.',
    createdAt: '2023-08-20 11:00:00',
    updatedAt: '2025-01-14 16:00:00',
    updatedBy: 'Rahul Prasad',
  },
  {
    id: 'agipl-srv-003',
    assetId: 'AGIPL-SRV-001',
    company: 'AGIPL' as const,
    assetType: 'Server',
    assetNumber: 'AG-IT-2021-001',
    status: 'ACTIVE' as const,
    condition: 'NEW' as const,
    assignedEmployeeName: 'Sameer Tupe (IT Infrastructure)',
    assetUserName: 'srv-agipl-erp',
    department: 'Information Technology',
    location: 'Hadapsar Server Room - Rack #01',
    ipAddress: '192.168.10.10',
    serialNumber: 'PE-R740-99238',
    manufacturer: 'Dell',
    model: 'PowerEdge R740 2U Server',
    processor: 'Dual Intel Xeon Silver 4210R (20 Cores Total)',
    storage: '4x 1.2TB SAS 10K RPM in RAID 10 (Hardware PERC H740P)',
    ram: '64GB RDIMM 2933MT/s Dual Rank',
    motherboard: 'Dell Server Board C620',
    display: 'KVM Switch Console (Rack Mounted)',
    displaySize: '17 inch Rack Console',
    lanCard: 'Broadcom 5720 Quad Port 1GbE BASE-T',
    upsBattery: 'APC Smart-UPS RT 3000VA Online with SNMP',
    windowsVersion: 'Windows Server 2022 Standard (16 Core)',
    msOffice: 'N/A - Dedicated Server',
    escan: 'eScan Server Security Suite Lic #ESC-SRV-01',
    vendor: 'Wipro Infotech Pune',
    purchaseDate: '2021-03-10',
    purchaseCost: 385000,
    invoiceNumber: 'WPR-PUN-2021-039',
    expectedLife: 6,
    warrantyStart: '2021-03-10',
    warrantyEnd: '2024-03-09',
    amcStart: '2024-03-10',
    amcEnd: '2027-03-09',
    lastServiceDate: '2025-06-20',
    remarks: 'Hosts Primary ERP Database, Measurement Calibration DB, and Active Directory Domain Controller.',
    createdAt: '2021-03-10 09:00:00',
    updatedAt: '2025-06-20 18:00:00',
    updatedBy: 'Sameer Tupe',
  },
  {
    id: 'asspl-lap-001',
    assetId: 'ASSPL-LAP-001',
    company: 'ASSPL' as const,
    assetType: 'Laptop',
    assetNumber: 'AS-IT-2023-019',
    status: 'ACTIVE' as const,
    condition: 'NEW' as const,
    assignedEmployeeName: 'Mahesh Shinde',
    assetUserName: 'mshinde',
    department: 'Sales & Field Services',
    location: 'Pimpri Sales HQ & Field Travelling',
    ipAddress: '192.168.20.72',
    serialNumber: 'LN-TP-E14-4421',
    manufacturer: 'Lenovo',
    model: 'ThinkPad E14 Gen 4',
    processor: 'AMD Ryzen 5 5625U (6 Cores / 12 Threads)',
    storage: '512GB M.2 PCIe Gen4 NVMe SSD',
    ram: '16GB DDR4 3200MHz',
    motherboard: 'Lenovo ThinkPad AMD Platform',
    display: '14" FHD IPS (1920x1080) 300 nits Antiglare',
    displaySize: '14 inch',
    lanCard: 'Realtek RTL8111H Gigabit + Wi-Fi 6',
    upsBattery: '57Wh Battery (Health 95%)',
    windowsVersion: 'Windows 11 Pro 64-bit',
    msOffice: 'Microsoft Office 2021 Home & Business',
    escan: 'eScan Corporate Edition (Lic #ESC-AS-112)',
    vendor: 'CompuCom Pune',
    purchaseDate: '2023-04-12',
    purchaseCost: 68000,
    invoiceNumber: 'CC-PMP-2023-882',
    expectedLife: 4,
    warrantyStart: '2023-04-12',
    warrantyEnd: '2026-04-11',
    amcStart: '',
    amcEnd: '',
    lastServiceDate: '2024-11-05',
    remarks: 'Issued to Field Service Engineer for on-site gauge servicing & calibration demos.',
    createdAt: '2023-04-12 10:00:00',
    updatedAt: '2024-11-05 12:00:00',
    updatedBy: 'Rahul Prasad',
  },
  {
    id: 'asspl-dsk-002',
    assetId: 'ASSPL-DSK-002',
    company: 'ASSPL' as const,
    assetType: 'Desktop',
    assetNumber: 'AS-IT-2020-008',
    status: 'UNDER REPAIR' as const,
    condition: 'NEW' as const,
    assignedEmployeeName: 'Suresh Patil',
    assetUserName: 'spatil',
    department: 'Accounts & Billing',
    location: 'Pimpri Office - Finance Section',
    ipAddress: '192.168.20.33',
    serialNumber: 'HP-PRO-280-G4',
    manufacturer: 'HP',
    model: 'HP 280 G4 Microtower',
    processor: 'Intel Core i3-9100 (4 Core, 3.60 GHz)',
    storage: '256GB SATA SSD + 500GB HDD',
    ram: '8GB DDR4 2666MHz',
    motherboard: 'HP H370 Chipset',
    display: 'HP 20" LED Monitor V20 HD',
    displaySize: '20 inch',
    lanCard: 'Realtek PCIe Gigabit Family',
    upsBattery: 'Luminous 600VA Standalone UPS (Faulty Battery)',
    windowsVersion: 'Windows 10 Pro 64-bit 22H2',
    msOffice: 'Microsoft Office 2019 Home & Business',
    escan: 'eScan Corporate Edition (Lic #ESC-AS-094)',
    vendor: 'Softmart Solutions Pune',
    purchaseDate: '2020-02-18',
    purchaseCost: 42000,
    invoiceNumber: 'INV-SM-2020-1920',
    expectedLife: 5,
    warrantyStart: '2020-02-18',
    warrantyEnd: '2023-02-17',
    amcStart: '2023-02-18',
    amcEnd: '2026-02-17',
    lastServiceDate: '2026-08-05',
    remarks: 'Power Supply Unit (PSU) failure and UPS battery dead. Sent to vendor for PSU replacement.',
    createdAt: '2020-02-18 09:00:00',
    updatedAt: '2026-08-05 11:30:00',
    updatedBy: 'Rahul Prasad',
  },
  {
    id: 'asspl-prn-003',
    assetId: 'ASSPL-PRN-001',
    company: 'ASSPL' as const,
    assetType: 'Printer / MFP',
    assetNumber: 'AS-IT-2022-088',
    status: 'ACTIVE' as const,
    condition: 'NEW' as const,
    assignedEmployeeName: 'Shared Network (Admin Office)',
    assetUserName: 'mfp-asspl-pimpri',
    department: 'Administration',
    location: 'Pimpri Office - Reception / Admin Bay',
    ipAddress: '192.168.20.200',
    serialNumber: 'CN-IR-2625-781',
    manufacturer: 'Canon',
    model: 'imageRUNNER 2625i Multi-Function Network Copier',
    processor: 'Canon Dual Core Custom CPU 1.75GHz',
    storage: '64GB eMMC onboard',
    ram: '2.0GB RAM',
    motherboard: 'Canon Embedded MFP Controller',
    display: '7 inch TFT LCD WVGA Color Touch Panel',
    displaySize: '7 inch Touch',
    lanCard: '1000Base-T/100Base-TX/10Base-T Ethernet',
    upsBattery: 'APC 2KVA Line Interactive UPS',
    windowsVersion: 'Embedded Linux MFP OS',
    msOffice: 'N/A',
    escan: 'N/A',
    vendor: 'Canon India Direct Pune',
    purchaseDate: '2022-09-10',
    purchaseCost: 145000,
    invoiceNumber: 'CAN-IND-2022-901',
    expectedLife: 7,
    warrantyStart: '2022-09-10',
    warrantyEnd: '2023-09-09',
    amcStart: '2023-09-10',
    amcEnd: '2026-09-09',
    lastServiceDate: '2026-06-12',
    remarks: 'Under comprehensive per-page AMC with Canon Service Pune.',
    createdAt: '2022-09-10 14:00:00',
    updatedAt: '2026-06-12 15:00:00',
    updatedBy: 'Rahul Prasad',
  },
  {
    id: 'onyx-dsk-001',
    assetId: 'ONYX-DSK-001',
    company: 'ONYX' as const,
    assetType: 'Desktop',
    assetNumber: 'OX-IT-2024-004',
    status: 'ACTIVE' as const,
    condition: 'NEW' as const,
    assignedEmployeeName: 'Nitin Sawant',
    assetUserName: 'nsawant',
    department: 'CNC Machining & CAM',
    location: 'Chakan Plant - Machine Shop Station 3',
    ipAddress: '192.168.30.15',
    serialNumber: 'DL-OPT-7010-332',
    manufacturer: 'Dell',
    model: 'OptiPlex Tower 7010',
    processor: 'Intel Core i5-13500 (14 Cores, up to 4.80 GHz)',
    storage: '1TB M.2 PCIe NVMe SSD',
    ram: '16GB DDR5 4800MHz',
    motherboard: 'Dell B660 Chipset',
    display: 'Dell 27" QHD Monitor P2723D',
    displaySize: '27 inch QHD',
    lanCard: 'Intel Gigabit Ethernet',
    upsBattery: 'Numeric 1000VA Heavy Duty Industrial UPS',
    windowsVersion: 'Windows 11 Pro 64-bit',
    msOffice: 'Microsoft Office 2021 Home & Business',
    escan: 'eScan Corporate Edition (Lic #ESC-OX-021)',
    vendor: 'Softmart Solutions Pune',
    purchaseDate: '2024-01-25',
    purchaseCost: 79000,
    invoiceNumber: 'INV-SM-2024-0412',
    expectedLife: 5,
    warrantyStart: '2024-01-25',
    warrantyEnd: '2027-01-24',
    amcStart: '',
    amcEnd: '',
    lastServiceDate: '2024-01-25',
    remarks: 'Industrial rugged enclosure installed for Chakan machine shop dust protection.',
    createdAt: '2024-01-25 11:00:00',
    updatedAt: '2024-01-25 11:00:00',
    updatedBy: 'Sameer Tupe',
  },
  {
    id: 'onyx-lap-002',
    assetId: 'ONYX-LAP-002',
    company: 'ONYX' as const,
    assetType: 'Laptop',
    assetNumber: 'OX-IT-2023-018',
    status: 'IN STOCK' as const,
    condition: 'NEW' as const,
    assignedEmployeeName: '',
    assetUserName: '',
    department: 'IT Buffer / Spare Pool',
    location: 'Chakan Plant - IT Store Room Cupboard A',
    ipAddress: 'DHCP Reserved 192.168.30.99',
    serialNumber: 'LN-TP-L14-9912',
    manufacturer: 'Lenovo',
    model: 'ThinkPad L14 Gen 3',
    processor: 'Intel Core i5-1235U (10 Core)',
    storage: '512GB SSD',
    ram: '16GB DDR4',
    motherboard: 'Lenovo ThinkPad',
    display: '14" FHD Antiglare',
    displaySize: '14 inch',
    lanCard: 'Intel Wi-Fi 6 AX201',
    upsBattery: '57Wh (Health 98%)',
    windowsVersion: 'Windows 11 Pro',
    msOffice: 'Microsoft Office 2021 H&B',
    escan: 'eScan Corporate Lic #ESC-OX-034',
    vendor: 'Dynalog India Pvt Ltd',
    purchaseDate: '2023-11-10',
    purchaseCost: 71500,
    invoiceNumber: 'DYN-PUN-1188',
    expectedLife: 4,
    warrantyStart: '2023-11-10',
    warrantyEnd: '2026-11-09',
    amcStart: '',
    amcEnd: '',
    lastServiceDate: '2026-07-20',
    remarks: 'Formatted with base company image, ready for immediate deployment to new engineer.',
    createdAt: '2023-11-10 14:00:00',
    updatedAt: '2026-07-20 16:30:00',
    updatedBy: 'Rahul Prasad',
  },
  {
    id: 'agipl-dsk-004-ret',
    assetId: 'AGIPL-DSK-004',
    company: 'AGIPL' as const,
    assetType: 'Desktop',
    assetNumber: 'AG-IT-2018-011',
    status: 'RETIRED' as const,
    condition: 'OLD' as const,
    assignedEmployeeName: 'Former Employee (Pooja R.)',
    assetUserName: 'prane_archived',
    department: 'Human Resources (Archived)',
    location: 'Hadapsar Plant - IT Scrap / Quarantine Yard',
    ipAddress: 'Decommissioned',
    serialNumber: 'HP-DX-2018-0991',
    manufacturer: 'HP',
    model: 'HP ProDesk 400 G4',
    processor: 'Intel Core i3-7100 (7th Gen)',
    storage: '500GB Western Digital Blue HDD',
    ram: '4GB DDR4',
    motherboard: 'HP H110',
    display: 'HP 18.5" LED',
    displaySize: '18.5 inch',
    lanCard: 'Realtek PCIe Fast Ethernet',
    upsBattery: 'Decommissioned',
    windowsVersion: 'Windows 10 Pro 32-bit (Deprecated)',
    msOffice: 'MS Office 2013',
    escan: 'Expired',
    vendor: 'Local Pune Dealer',
    purchaseDate: '2018-04-10',
    purchaseCost: 34000,
    invoiceNumber: 'INV-2018-099',
    expectedLife: 5,
    warrantyStart: '2018-04-10',
    warrantyEnd: '2021-04-09',
    amcStart: '',
    amcEnd: '',
    lastServiceDate: '2023-01-15',
    remarks: 'Completed 6+ years service lifecycle. Disk wiped securely with DoD 5220.22-M 3-pass standard on retirement.',
    createdAt: '2018-04-10 10:00:00',
    updatedAt: '2024-05-12 11:00:00',
    updatedBy: 'Sameer Tupe',
  },
  {
    id: 'onyx-net-003',
    assetId: 'ONYX-NET-001',
    company: 'ONYX' as const,
    assetType: 'Network Switch',
    assetNumber: 'OX-IT-2022-091',
    status: 'ACTIVE' as const,
    condition: 'NEW' as const,
    assignedEmployeeName: 'IT Infrastructure (Chakan)',
    assetUserName: 'sw-core-chakan',
    department: 'Information Technology',
    location: 'Chakan Plant - Central Rack Room',
    ipAddress: '192.168.30.2',
    serialNumber: 'CS-CBS350-48P-991',
    manufacturer: 'Cisco',
    model: 'Cisco Business 350 Series 48-Port PoE+ Gigabit Managed Switch',
    processor: 'Cisco ARM v7 Dual Core 800MHz',
    storage: '256MB Flash',
    ram: '512MB RAM',
    motherboard: 'Cisco Switchboard with 4x 10G SFP+ Uplinks',
    display: 'LED Status Indicators & Console Port',
    displaySize: '1U Rackmount',
    lanCard: '48x 10/100/1000 PoE+ Ports',
    upsBattery: 'Connected to Central Online UPS',
    windowsVersion: 'Cisco Switch Firmware v3.2.0.84',
    msOffice: 'N/A',
    escan: 'N/A',
    vendor: 'Wipro Infotech Pune',
    purchaseDate: '2022-11-15',
    purchaseCost: 112000,
    invoiceNumber: 'WPR-2022-119',
    expectedLife: 7,
    warrantyStart: '2022-11-15',
    warrantyEnd: '2027-11-14',
    amcStart: '',
    amcEnd: '',
    lastServiceDate: '2025-05-10',
    remarks: 'Core switch powering industrial inspection cameras and PoE access points.',
    createdAt: '2022-11-15 10:00:00',
    updatedAt: '2025-05-10 14:00:00',
    updatedBy: 'Sameer Tupe',
  }
];

export const INITIAL_ASSETS: Asset[] = rawAssetsData.map(raw => {
  const assetAge = calculateAssetAge(raw.purchaseDate);
  const expectedReplacementDate = calculateExpectedReplacementDate(raw.purchaseDate, raw.expectedLife);
  const depreciatedValue = calculateDepreciatedValue(raw.purchaseCost, raw.purchaseDate, raw.expectedLife);
  const warrantyAlert = checkWarrantyAlert(raw.warrantyEnd).isAlert;
  const replacementAlert = checkReplacementAlert(raw.purchaseDate, raw.expectedLife, expectedReplacementDate);

  return {
    ...raw,
    assetAge,
    expectedReplacementDate,
    depreciatedValue,
    warrantyAlert,
    replacementAlert,
  };
});

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    assetDocId: 'agipl-dsk-001',
    assetId: 'AGIPL-DSK-001',
    company: 'AGIPL',
    action: 'CREATED',
    details: 'Initial asset record registered in Accurate Group inventory system with Dell OptiPlex 7090 specifications.',
    performedBy: 'Sameer Tupe',
    performedByEmail: 'sameer.tupe@accurate.in',
    timestamp: '2022-06-15 10:00:00',
  },
  {
    id: 'log-002',
    assetDocId: 'agipl-dsk-001',
    assetId: 'AGIPL-DSK-001',
    company: 'AGIPL',
    action: 'ASSIGNED',
    details: 'Assigned to Vikas Kulkarni in Engineering & Design (CAD Room). Handover slip signed.',
    performedBy: 'Sameer Tupe',
    performedByEmail: 'sameer.tupe@accurate.in',
    timestamp: '2022-06-16 11:30:00',
  },
  {
    id: 'log-003',
    assetDocId: 'agipl-dsk-001',
    assetId: 'AGIPL-DSK-001',
    company: 'AGIPL',
    action: 'SERVICED',
    details: 'Annual routine maintenance performed by Softmart engineer. Internal dust cleaning and eScan definition update.',
    performedBy: 'Sameer Tupe',
    performedByEmail: 'sameer.tupe@accurate.in',
    timestamp: '2024-03-10 14:30:00',
  },
  {
    id: 'log-004',
    assetDocId: 'asspl-dsk-002',
    assetId: 'ASSPL-DSK-002',
    company: 'ASSPL',
    action: 'UPDATED',
    details: 'Status changed from ACTIVE to UNDER REPAIR due to Power Supply Unit (PSU) failure reported by Suresh Patil.',
    performedBy: 'Rahul Prasad',
    performedByEmail: 'rahulprashad7@gmail.com',
    timestamp: '2026-08-05 11:30:00',
  },
  {
    id: 'log-005',
    assetDocId: 'agipl-dsk-004-ret',
    assetId: 'AGIPL-DSK-004',
    company: 'AGIPL',
    action: 'RETIRED',
    details: 'Asset retired following 6-year operational lifecycle. Hard disk wiped to standard and moved to quarantine yard.',
    performedBy: 'Sameer Tupe',
    performedByEmail: 'sameer.tupe@accurate.in',
    timestamp: '2024-05-12 11:00:00',
  }
];

export const INITIAL_SERVICE_RECORDS: ServiceRecord[] = [
  {
    id: 'srv-001',
    assetDocId: 'agipl-dsk-001',
    assetId: 'AGIPL-DSK-001',
    serviceDate: '2024-03-10',
    serviceType: 'Routine Maintenance',
    vendor: 'Softmart Solutions Pune',
    cost: 1200,
    issueDescription: 'Scheduled preventative maintenance & thermal paste renewal.',
    actionTaken: 'Cleaned cabinet dust, renewed Arctic MX-4 thermal paste, updated BIOS to v1.18.0, scanned with eScan.',
    partsReplaced: 'None (Thermal paste refreshed)',
    nextFollowup: '2025-03-10',
    recordedBy: 'Sameer Tupe',
    createdAt: '2024-03-10 15:00:00',
  },
  {
    id: 'srv-002',
    assetDocId: 'asspl-dsk-002',
    assetId: 'ASSPL-DSK-002',
    serviceDate: '2026-08-05',
    serviceType: 'Hardware Repair',
    vendor: 'CompuCom Pune',
    cost: 3500,
    issueDescription: 'System suddenly powered off with burning smell from PSU; PC not turning on.',
    actionTaken: 'Diagnosed dead 310W internal HP Power Supply Unit. Dispatched to CompuCom service center for OEM replacement.',
    partsReplaced: 'HP 310W 80-Plus Gold PSU (under replacement)',
    nextFollowup: '2026-08-22',
    recordedBy: 'Rahul Prasad',
    createdAt: '2026-08-05 12:00:00',
  },
  {
    id: 'srv-003',
    assetDocId: 'asspl-prn-003',
    serviceDate: '2026-06-12',
    assetId: 'ASSPL-PRN-001',
    serviceType: 'Routine Maintenance',
    vendor: 'Canon India Direct Pune',
    cost: 0,
    issueDescription: 'Quarterly AMC servicing and drum unit inspection.',
    actionTaken: 'Drum cleaner blade replaced, laser glass cleaned, pickup roller cleaned, total meter count logged at 48,220 pages.',
    partsReplaced: 'Canon Drum Cleaning Blade (Covered under AMC)',
    nextFollowup: '2026-09-12',
    recordedBy: 'Rahul Prasad',
    createdAt: '2026-06-12 15:30:00',
  }
];
